version: "3.9"

services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      API_TOKEN: $API_TOKEN  # defaults to None

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: telegram_bot_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db